### ISSUE TITLE
invalid pass number with unity 5.1

### ISSUE THREAD

**Issue by itsjesseyo** [Chman/SMAA-Unity#4]
I just updated to the latest unity (5.1) and suddenly I am getting this error:

Invalid pass number (4) for Graphics.Blit. Material=Hidden/Subpixel Morphological Antialiasing, npasses=1
UnityEngine.Graphics:Blit(Texture, RenderTexture, Material, Int32)
Smaa.SMAA:OnRenderImage(RenderTexture, RenderTexture) (at Assets/VENDOR/SMAA/Scripts/SMAA.cs:245)
UnityEngine.Camera:Render()
CameraBodyEditor:UpdateRenderTexture() (at Assets/Cinema Suite/Cinema Pro Cams/Scripts/Editor/CameraBodyEditor.cs:520)
CameraBodyEditor:DrawCameraPreview() (at Assets/Cinema Suite/Cinema Pro Cams/Scripts/Editor/CameraBodyEditor.cs:454)
CameraBodyEditor:OnInspectorGUI() (at Assets/Cinema Suite/Cinema Pro Cams/Scripts/Editor/CameraBodyEditor.cs:200)
UnityEditor.DockArea:OnGUI()

**Comment by Chman** [comment]
Works here.

Could you select `/SMAA/Shaders/SMAA.shader` in the project panel and look for shader compilation errors in the Inspector ?
